---
title: "Lead Isotope Provenance Functions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Lead Isotope Provenance Functions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: references.bib
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(ASTR)
```

# Introduction

Provenance studies using lead isotope analyis, uses three rations of the four
isotope rations of lead. These are: `206Pb/204Pb`, `207Pb/204Pb`, `208Pb/204Pb`.
The isotopic compositions in LIA are initially represented in a 
three-dimensional coordinate system [@albarede24].

However, the current approaches to lead isotope analysis rely heavily on visual inspection or simple distance-based metrics, methods that struggle to capture the complex structure and overlaps within large isotopic datasets. As a result, provenance interpretations often differ sharply between researchers, even when studying the same hoards. By contrast, a algorithmic framework provides a systematic, data-driven alternative that detects patterns, reduces overlaps, and minimizes subjective interpretation. This shift not only improves reproducibility but also opens the door to identifying previously unrecognised ore sources [@shnyr26].

The lead Isotope provencnce functions follow 
[the ASTR schema](VG.ASTRschema.0.0.2.html), and only take in ASTR objects.
Working with ASTR objects is described [here](ASTR.showcase.html)

For the pourposes of demonstration, lead isotope data from the Tel Dor silver hoards will be used [@shnyr26] as sample data ad a modified [GlobaLID data base](https://globalid.dmt-lb.de/), containing the lead isotope rations, grouped by the Political province/region variable will be used as referendce data.

```{R tel_dor demo}
tel_dor
```

```{R GlobaLID_ASTR demo}
GlobaLID_ASTR
```

# Provencnace Functions

There are two main methods which can be used for provenance analysis.
The first is the standard euclidean distance function, with added mass 
fractionation correction [@albarede24], and the second is a machine learning
methods, where pre-train a extrema gradient boosting (XGBoost) model, and get the provenance probabilities.
In both case we use both cases we used the sample and reference data, which are 
ASTR obects [@shnyr26].

## Creaing reference data object

But before we use functions, we need to create the transform the reference data
to a `ASTR_Pbiso_ref_data`. This can be achieved using `as_pbiso_ref_data()` function, which removes all vraibles, except the `ASTR_context` designated as the grouping variable, and the lead isotope rations.
The reference data set can some times have gorups with too few samples for relevant analsysis. It is advised that these groups be excluded from the refence data set.
The `min_groupsize` attribute can be used to set a cutoff intiger value, and only groups that have samples exceeding `min_groupsize` will be retained.

```{R as_pbiso_ref_data demo}
GlobalLID_ASTR_ref <- as_pbiso_ref_data(GlobaLID_ASTR, group = "Political province/region", min_groupsize = 5)
GlobalLID_ASTR_ref
```

## Stadandared Euclidean distance

The standard model for estimating three-dimensional distances for lead isotope values involves measuring the Euclidean distance between two vectors, $\vec{x}$ and $\vec{x}'$. This calculation follows the established formula:$$d(\vec{x}, \vec{x}') = \sqrt{\sum_{i=1}^{n} (x_i - x'_i)^2}$$

This is the method used by the function `isoprov_dist()` when the `dist_type` value is set to `"ed"` which stands for 'Eucilidian distance'.

According to @A.D.B+24, the standard method fails to account for statistical errors. These errors are addressed by weighting the data with the full covariance matrix $W$ of the NIST 981 lead isotope reference material. The adjusted distance is calculated as:$$d = \sqrt{(\mathbf{x} - \mathbf{x}')^T W^{-1} (\mathbf{x} - \mathbf{x}')}$$In this formula, $T$ denotes the transpose of the vector.

```{R euc_dis function demo}
euc_dist(tel_dor, GlobalLID_ASTR_ref, .n = 1)
```

## Algorithum acounting for Mass-dependant fractionation

Recently, @albarede24 introduced a Pb-isotope provenance algorithm that significantly improves the correction of mass-dependent fractionation, a long-standing challenge in lead isotope analysis.

The methodology utilizes the distance $d_i$ between an artifact and the mass-dependent fractionation line passing through ore $i$. This is implemented by setting the dist_type parameter to "mfd". Provided lead isotope ratios differ by less than one decimal point, respective fractionation lines are considered parallel. The distance $d_i$ is computed using the vector $\vec{\Delta X_i} = (\vec{x}_i - \vec{x}_0)$, where $\vec{x}_0$ represents the artifact and $\vec{x}_i$ represents the ore.The artifact is represented as:$$\vec{x}_0=\left[\left(^{206}Pb/^{204}Pb\right)_0,\left(^{207}Pb/^{204}Pb\right)_0,\left(^{208}Pb/^{204}Pb\right)_0\right]$$The ore is represented as:$$\vec{x}_i=\left[\left(^{206}Pb/^{204}Pb\right)_i,\left(^{207}Pb/^{204}Pb\right)_i,\left(^{208}Pb/^{204}Pb\right)_i\right]$$The mass-dependent fractionation line is defined by the vector $\vec{v}$:$$\vec{v}=\left[2\left(^{206}Pb/^{204}Pb\right)_0,3\left(^{207}Pb/^{204}Pb\right)_0,4\left(^{208}Pb/^{204}Pb\right)_0\right]$$The digits in $\vec{v}$ correspond to the atomic mass differences of the isotopes. With $\vec{n} = \vec{v}/||\vec{v}||$ as the unit vector, distance $d_i$ is calculated via the cross-product:$$d_i = ||\vec{\Delta X_i} \times \vec{n}||$$The fractionation factor $f_i$ is computed as a dot product:$$f_i = \vec{\Delta X_i} \cdot \vec{n}$$To obtain a dimensionless distance, the error matrix $W$ is defined as:$$W=
\begin{bmatrix}
2x^*_x & 0 & 0\\
0 & 3x^*_y & 0\\
0 & 0 & 4x^*_z\\
\end{bmatrix}
\begin{bmatrix}
1 & 0.96 & 0.94\\
0.96 & 1 & 0.96\\
0.94 & 0.96 & 1
\end{bmatrix}
\begin{bmatrix}
2x^*_x & 0 & 0\\
0 & 3x^*_y & 0\\
0 & 0 & 4x^*_z\\
\end{bmatrix}$$The outer matrices are diagonal standard deviation matrices for common lead, with a fractionation factor $s$ of 0.001. Squared distances $|d|^2$ are normalized to the two-dimensional shadow of $W$ perpendicular to $\vec{n}$. This requires Gram-Schmidt orthogonalization to find perpendicular vectors. Since $W$ is derived from reference materials, this metric is not a formal Mahalanobis distance. Normalized squared distances follow a chi-squared distribution with two degrees of freedom. Consequently, ores with $|d|^2$ values exceeding 5.99 are rejected at the 95% confidence level.

```{R mf_dist function demo}
mf_dist(tel_dor, GlobalLID_ASTR_ref, .n = 1, s = 0.001)
```

The `pb_iso_prov_dist()` provides a wrapper for them and allows to calculate all age models simultaneously. This an all functions also use the `as_pbiso_ref_data()`
function, regular `ASTR objects` to lead isotope refrence data.

```{R pb_iso_prov_dist function demo}
pb_iso_prov_dist(tel_dor, GlobaLID_ASTR, ref_group = "Political province/region",
                 dist_type = "all")
```

## Machine Leanring Model

Models trained using `pb_iso_train_data()` go through a data processing pipe-line 
as outlined by [@shnyr26]:
- Outlier identification
- SMOTE data imputation
- XGBoost Classification and model training.

### Outlier identification

Outlier identification and elimination is achieved with the help of 
DBSCAN (Density-Based Spatial Clustering of Applications with Noise) algorithm
which is able to identify outliers and subgroup patterns within regions.
DBSCAN facilitated the removal of outliers and the formation of clusters within lead isotopic data, reducing potential overlaps between regions.
The neighbourhood radius ($\epsilon$) determines the most appropriate value for clustering.
This is controlled by the argument `.eps`.

To ensure reliability only samples over a certain value should be clsutered.
This is controlled by the argument `.minSize`.

### SMOTE data imputation

SMOTE (synthetic minority over-sampling technique) is a valuable methodology that helps by creating synthetic data points for the minority class through a kind of data interpolation.
Using SMOTE effectively enables ML models to better identify hidden patterns in the data, leading to more accurate predictions.
The k-neighbor (KNN) parameter in the SMOTE algorithm controls how many nearby data points are considered when generating synthetic samples for minority classes. A smaller k-neighbors value focuses on closer neighbors, while a larger value includes a broader set of neighbors, affecting the diversity of synthetic samples [@chawla02].

### XGBoost Classification and model training

The XGBoost algorithm was applied to train the binary classification model, using the three isotopic ratios as input features and the resulting. regional cluster names—previously derived from DBSCAN—as target labels. This iterative process involved encoding the data, applying SMOTE, and training the XGBoost model for each cluster. The final model, is list of individual XGBoost modles which can effectively distinguished between target and non-target classes, leveraging the refined dataset for reliable predictions.

```{R pb_iso_train_data demo, eval=FALSE}
ml_modle <- pb_iso_train_data(GlobalLID_ASTR_ref)
```

### Machien Learning based provenance prediction

Providing the sample data `ASTR` object with the model created using the
`pb_iso_train_data()` outputs a new `ASTR` object containing the probabilities
of provenance for a given refrence data groups.

```{R pb_iso_prov_predict demo}
pb_iso_prov_predict(tel_dor, model_list = ml_model, .top = 1)
```

# Refrence
